### PR TITLE
Abdal Autoit

### PR DESCRIPTION
**Pull request by shahriaarrr**
add Abdal Autoit program

more info: www.hackers.zone

### CODE REVIEW

**Comment by parsampsh** [comment]
I think moving `about.txt` to `README.md` is better.

**Comment by BlackIQ** [comment]
> I think rename `about.txt` to `README.md` is better.

Agreed , we can put information about the language .

**Comment by parsampsh** [comment]
Also please rename `Abdal Autoit` folder to `Abdal-Autoit`(use `-` instead of space)

**Comment by shahriaarrr** [comment]
Ok. Necessary changes were applied

**Comment by shahriaarrr** [comment]
https://github.com/BlackIQ/Hello-World/pull/60#issuecomment-765209012

I have done it

**Comment by shahriaarrr** [comment]
https://github.com/BlackIQ/Hello-World/pull/60#issuecomment-765216410

I have done it

**Comment by parsampsh** [comment]
Thanks!

**Pull request merged**
