### PR TITLE
add F# and Scratch and OBJECT-C

### PR DESCRIPTION
**Pull request by shahriaarrr**
1-Add Flask and Django project
2-add F# and Scratch and OBJECT-C
3-fix the bug
4-Edit C++ program and add comment

### CODE REVIEW

**Comment by BlackIQ** [comment]
Hi ,

Thanks for P.R .
You are friend with Mehran . Right !?

Live long and prosper .
Amir .

**Comment by shahriaarrr** [comment]
Yes.Mehran is my best friend((Brother is a more appropriate word))

And I am very happy that I was able to participate in this project

Wishing you success and health, dear Amir Hossein.
Shahriar.

**Comment by BlackIQ** [comment]
TNX Shahriar .
It was an honor to have you in the project .
I with be friend forever .

Smile and use mask .
May the force be with you .
Amir .

**Comment by shahriaarrr** [comment]
❤

**Pull request merged**
