### PR TITLE
Added Contributers table

### PR DESCRIPTION
**Pull request by amireshoon**
I created a `contributers.py` file to generate a table of people who added languages to this repository.
`contributers.py` create a table from people who contribute and added Hello World language
for this repository. Which the first column is the name and the second one is how many language
contributor added to this repo and also if a contributor added more than 5 language
contributor will receive a badge after his name

### CODE REVIEW

**Comment by amireshoon** [comment]
@parsampsh Don't merge it yet.
issues:
- [ ] Multiple names for one contributor

**Review by parsampsh — CHANGES_REQUESTED** [review]
There is a typo. `contributErs` should be renamed to `contributOrs`.

**Comment by parsampsh** [comment]
> @parsampsh Don't merge it yet.
> issues:
> 
>     * [ ]  Multiple names for one contributor

Yes. i am thinking about it.

**Comment by amireshoon** [comment]
> > @parsampsh Don't merge it yet.
> > issues:
> > ```
> > * [ ]  Multiple names for one contributor
> > ```
> 
> Yes. i am thinking about it.

We can create arrays of dicts with contributors names and added languages then for those who already were in the dict just update dict instead of adding a new dict to the array

**Comment by parsampsh** [comment]
fixed. please wait to i push it.

**Comment by amireshoon** [comment]
> Is good rename `CONTRIBUTORS.md` to `CONTRIBUTORS_LIST.md`? this name is very like `CONTRIBUTING.md`.

Okay I'll do that

**Comment by parsampsh** [comment]
I think its reay. but have you any idea for sorting this list? or the current sort is good? I think its good to sort by count of added languages

**Comment by amireshoon** [comment]
> r the current sort is go

I think so too. But it's not too necessary

**Comment by parsampsh** [comment]
Done.

**Review by parsampsh — APPROVED** [review]

**Comment by amireshoon** [comment]
> Done.

Nice thanks.

**Pull request merged**
