### PR TITLE
Added github actions and some changes in gen-readme.py

### PR DESCRIPTION
**Pull request by amireshoon**
I've added auto-generate readme via [GitHub action](https://github.com/amireshoon/Hello-World/actions). In this way, the contributor doesn't have to run the `gen-readme.py` file on the local machine instead GitHub actions automatically run that and push a new readme file into the repo.
Note that you have to change `git configs` in `/.github/workflows/python-app.yml`
I also improve gen-readme.py to replace spaces with a dash.
Also, I added some language Hello world during the test.

### CODE REVIEW

**Comment by parsampsh** [comment]
I think the github actions for generating readme is great! Thanks.

**Comment by parsampsh** [comment]
@BlackIQ  please don't merge it for now. i need to add something to gen-readme.py

**Comment by amireshoon** [comment]
@parsampsh I think it's better to rename the folders with any sort of whitespace to dash-separated names.

**Comment by parsampsh** [comment]
> @parsampsh I think it's better to rename the folders with any sort of whitespace to dash-separated names.

Yes. exactly i wanna do this :)

**Comment by parsampsh** [comment]
Done

**Comment by parsampsh** [comment]
Thanks Amir. I Think this is ready to merge. @BlackIQ what's your say?

**Comment by amireshoon** [comment]
@parsampsh I'm glad you liked it.

**Comment by parsampsh** [comment]
> @parsampsh I'm glad you liked it.

I Like automation :)

**Comment by parsampsh** [comment]
I Think everything is ready. I'll merge it.

**Comment by parsampsh** [comment]
github action looks has some problems. can you check it @amireshoon?

**Comment by parsampsh** [comment]
No. i checked it again. it's ok :)

**Comment by amireshoon** [comment]
@parsampsh No, it's not an issue. When `readme.md` Is fully updated and there is nothing to commit git returns an exit with code 1. In the config file, I flagged it as not a failure.

**Pull request merged**
