### PR TITLE
Adds Typescript Courses and Resources

### PR DESCRIPTION
**Pull request by jdun28**
This PR adds two courses to learn typescript as well as helpful resources for learning Typescript. Updates the `info.json` to include author as creator and updates TODO to show resources and courses as `Done!`

Hacktoberfest 2022 contribution

### CODE REVIEW

**Comment by jdun28** [comment]
@BlackIQ for Review for hacktoberfest. Thanks in advance!

**Comment by BlackIQ** [comment]
Hi Jen,

You did great. Sorry for my late for merging your 2 prs.
Again, it is so nice having you here and I hope to make your goal in hacktoberfest!

Can I ask you a question?
When you wrote you are from **Olympia**, is it true?

May the force be with you.
Amir.

**Comment by jdun28** [comment]
@BlackIQ Yep, I am in Olympia! :D

**Comment by BlackIQ** [comment]
Ok, can we have a talk in Telegram or WhatsApp?
Thanks.

**Pull request merged**
