### PR TITLE
Added ASCII

### PR DESCRIPTION
**Pull request by nhelchitnis**
added ASCII

### CODE REVIEW

**Comment by BlackIQ** [comment]
Hi. Why did you closed it?

**Comment by nhelchitnis** [comment]
I just felt like it probably was not good enough

**Comment by nhelchitnis** [comment]
If you don’t want it then I can close it again

**Comment by BlackIQ** [comment]
Why did you think like that?

It is fantastic, beautiful and even new in this repository. I’ll merge it.

and next time don’t think like now. You did your best and I appreciate it.

Good luck next time my friend.

❤️

**Comment by nhelchitnis** [comment]
Thanks

**Pull request merged**
