### PR TITLE
Added JSF style programming in JS.

### PR DESCRIPTION
**Pull request by ali0gamer1**

### CODE REVIEW

**Comment by parsampsh** [comment]
come on man, are you kidding us? :))))

**Comment by BlackIQ** [comment]
> come on man, are you kidding us? :))))

He did that before too .
But deleted .

**Comment by parsampsh** [comment]
I Think this is cool and able to merge :)

**Comment by BlackIQ** [comment]
Have no problem .

**Comment by BlackIQ** [comment]
It is like branfuck too :)

**Comment by ali0gamer1** [comment]
> > come on man, are you kidding us? :))))
> 
> He did that before too .
> But deleted .

> > come on man, are you kidding us? :))))
> 
> He did that before too .
> But deleted .

its hard for me to express this in english... so:

.شرمنده من خودم نوبم یکاری کردم دیدم نشد بعد دوباره درخواست دادم
ازین به بعد هم سعی میکنم چیزای جدی تری بزارم.

**Pull request merged**
