### PR TITLE
Adds typescript language basic data types

### PR DESCRIPTION
**Pull request by MortezaHeydari97**
I'm begin typescript tutorial and I will complete it

### CODE REVIEW

**Comment by amireshoon** [comment]
Thank you for your contribution but I think it's not cool to write your name in the EOF's. your name will be added to repo `CONTRIBUTE_LIST.md` there is no need to write it there. Also instead of removing other contributor names add your name like this.
```json
{
    "creator": [
    {
        "title": "Amirhossein Mohammadi",
        "link": "https://github.com/BlackIQ"
    },{
        "title": "<name>",
        "link": "<profile_url>"
    }
   ]
} 
```
Multiple contributors will add soon.

**Comment by amireshoon** [comment]
Due to PR #123 Multiple contributors are now supported

**Comment by parsampsh** [comment]
Wait... I'm merging...

**Review by parsampsh — APPROVED** [review]
All done. @amireshoon Is it ok?

**Pull request merged**
