### PR TITLE
Create status table script for TODO.md

### PR DESCRIPTION
**Pull request by parsampsh**
The `status-table.py` script generates a table from status of languages and adds it to `TODO.md`. (This is not complete)

### CODE REVIEW

**Comment by parsampsh** [comment]
Now its ready.

**Comment by amireshoon** [comment]
It's a wonderful idea but we can do some more beatify to text such as removing checkboxes due it has no effect in here.
I can do it if it's ok with you @parsampsh

**Review by amireshoon — CHANGES_REQUESTED** [review]
It's a wonderful idea but we can do some more beatify to text such as removing checkboxes due it has no effect in here.
I can do it if it's ok with you @parsampsh

**Comment by parsampsh** [comment]
> It's a wonderful idea but we can do some more beatify to text such as removing checkboxes due it has no effect in here.
> I can do it if it's ok with you @parsampsh

Yes. i think check boxes are not needed :).

**Comment by amireshoon** [comment]
> > It's a wonderful idea but we can do some more beatify to text such as removing checkboxes due it has no effect in here.
> > I can do it if it's ok with you @parsampsh
> 
> Yes. i think check boxes are not needed :).

Alright then I work on it

**Comment by parsampsh** [comment]
> > > It's a wonderful idea but we can do some more beatify to text such as removing checkboxes due it has no effect in here.
> > > I can do it if it's ok with you @parsampsh
> > 
> > 
> > Yes. i think check boxes are not needed :).
> 
> Alright then I work on it

I removed checkbox. please make other changes and let me know :)

**Comment by amireshoon** [comment]
> > > > It's a wonderful idea but we can do some more beatify to text such as removing checkboxes due it has no effect in here.
> > > > I can do it if it's ok with you @parsampsh
> > > 
> > > 
> > > Yes. i think check boxes are not needed :).
> > 
> > 
> > Alright then I work on it
> 
> I removed checkbox. please make other changes and let me know :)

Done. I added some emojis and change some of the texts.

**Review by amireshoon — APPROVED** [review]
Everything seems to be great. I think @BlackIQ is not available what do you think about merging it @parsampsh ?

**Comment by parsampsh** [comment]
> Everything seems to be great. I think @BlackIQ is not available what do you think about merging it @parsampsh ?

I'll merge it.

**Comment by amireshoon** [comment]
No wait

**Comment by amireshoon** [comment]
now it's ready :smile:

**Pull request merged**
