### PR TITLE
Update C# 9

### PR DESCRIPTION
**Pull request by FriendsTmCo**
Add Hello World C# 9

### CODE REVIEW

**Comment by BlackIQ** [comment]
Hi ,

Console or Consoel !?

**Comment by Annahita2004** [comment]
C# is okay so it isn't necessary to merge

**Comment by parsampsh** [comment]
I Think this is better to move C# 9 to other file. for example `cs-9.cs`.

**Comment by parsampsh** [comment]
Looks some unresolvable conflicts. Please fix them or create new PR.

**Pull request closed without merging**
