### PR TITLE
Add BCPL

### PR DESCRIPTION
**Pull request by nhelchitnis**
I’ve added the BCPL Programming Language

### CODE REVIEW

**Comment by BlackIQ** [comment]
Thanks for your great pull requests!

**Comment by jacobsliam** [comment]
Your Welcome

**Comment by jacobsliam** [comment]
I am actually enjoying this a lot

**Comment by nhelchitnis** [comment]
Your welcome

**Comment by nhelchitnis** [comment]
I am really enjoying the hello world repo contibutions

**Pull request merged**
