### PR TITLE
Updated Solidity Folder With Info

### PR DESCRIPTION
**Pull request by swstkswstk**

### CODE REVIEW

**Comment by swstkswstk** [comment]
Please take this contribution under Hacktober fest 2024

**Comment by BlackIQ** [comment]
Thanks. If you work with Solidity, can I get help from you? Maybe could be work together.

**Comment by swstkswstk** [comment]
Hi! Thanks for considering me for collaboration on your Solidity project. I’d be interested to learn more about the project goals and the specific areas where you could use some support. Let me know if we can set up a time to discuss the details!

**Comment by swstkswstk** [comment]
Dude?

**Comment by BlackIQ** [comment]
I'll get in touch with you soon.

**Pull request merged**
